### ISSUE TITLE
运行后提示SSL is not supported.

### ISSUE THREAD

**Issue by LEAVN000000** [Snapmali/discord-monitor#11]
在自己电脑上测试没问题，放到服务器里就会报错

请输入配置文件路径，空输入则为默认(默认为config.json):

Logging in...
登录失败，请检查配置文件中各参数是否正确
Traceback (most recent call last):
  File "DiscordMonitor.py", line 491, in main
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "discord_bot\client.py", line 665, in start
  File "discord_bot\client.py", line 511, in login
  File "discord_bot\http.py", line 300, in static_login
  File "discord_bot\http.py", line 192, in request
  File "aiohttp\client.py", line 1138, in __aenter__
  File "aiohttp\client.py", line 535, in _request
  File "aiohttp\connector.py", line 542, in connect
  File "aiohttp\connector.py", line 907, in _create_connection
  File "aiohttp\connector.py", line 1140, in _create_direct_connection
  File "aiohttp\connector.py", line 950, in _get_ssl_context
RuntimeError: SSL is not supported.
请按任意键继续. . .

**Comment by Snapmali** [comment]
请尝试在python中运行
``` python
import ssl
ssl
```
查看是否返回ssl模块位置，如有报错建议重新安装python

**Comment by LEAVN000000** [comment]
> 请尝试在python中运行
> 
> ```python
> import ssl
> ssl
> ```
> 
> 查看是否返回ssl模块位置，如有报错建议重新安装python

可以返回，试了下重新安装python依然报错

**Comment by Snapmali** [comment]
你服务器使用的系统是？是自行编译还是直接运行的release中的exe？
如果是自行编译那么python版本是？
如果是直接运行，可以尝试下载源码编译运行，python打包成exe问题挺多的。

**Comment by LEAVN000000** [comment]
> 你服务器使用的系统是？是自行编译还是直接运行的release中的exe？ 如果是自行编译那么python版本是？ 如果是直接运行，可以尝试下载源码编译运行，python打包成exe问题挺多的。

感谢，自行编译后可以运行了
顺便一开始我自己的python版本是3.10，编译后会报错，后来重装了3.8就没问题

**Comment by Snapmali** [comment]
好的，我用3.10测试一下
